import type { Problem } from '../types'

/** Real problems from building and running this, from docs/ts-bench-task-board.md and docs/step7-real-model-run.md. */
export const problems: Problem[] = [
  {
    id: 'node-pin', tag: 'environment', title: 'Node version was recorded but never enforced', when: 'Task supply, T3',
    symptom: 'Nearly every trpc candidate was rejected, each with a large block of unrelated failing tests.',
    wrong_model: 'The fixes were incomplete, or the tests were flaky.',
    cause: 'Every install and test run used whatever Node the shell defaulted to (v24). The repository pins 22, and the two disagree about fetch internals. The failures spanned unrelated files, which was the tell.',
    fix: 'The adapter resolves the exact Node version through nvm, puts its bin directory first on PATH, and enables Corepack for that version.',
    lesson: 'Metadata you record but never enforce is a bug waiting for the machine to change.',
    evidence: 'The six newest trpc candidates all validated on the first try after the fix.',
  },
  {
    id: 'safety-path', tag: 'scoring', title: 'A passing gate that could not reach the safety path', when: 'Scoring, T6',
    symptom: 'The gold and empty gate passed, but nothing had tested the rule that restores test files an agent edits.',
    wrong_model: 'A passing top-level gate means the runner is correct.',
    cause: 'The human patch never touches test files by construction, so the restore step ran on an empty list every time. The gate structurally could not exercise it.',
    fix: 'A direct test tampers with a real test file, calls the restore, and checks the pristine content returns. Another checks a newly invented file is deleted.',
    lesson: 'Ask which code paths your gate can reach. A green check can hide zero coverage on the path that matters most.',
    evidence: '9 of 9 runner tests pass, including the tamper test.',
  },
  {
    id: 'docker-cache', tag: 'infrastructure', title: 'Caching the wrong thing in Docker', when: 'Sandbox, T12',
    symptom: "In a pnpm monorepo the test runner was missing, silently fell back to an unrelated global copy, and the harness reported a clean-looking but wrong result.",
    wrong_model: 'Cache node_modules by lockfile hash and skip the install once it looks ready.',
    cause: 'pnpm creates node_modules in many places, one per package. Skipping the install meant a fresh working tree never got its per-package folders.',
    fix: "Always run the install in full, and persist the package managers' own caches (pnpm store, npm cache, Corepack) in Docker volumes instead.",
    lesson: 'Cache the network, not the result. The design that looked obviously right was the wrong one.',
    evidence: 'Warm installs were 25 to 35 percent faster on a monorepo and 2.5 to 3 times faster on a single package.',
  },
  {
    id: 'compile-yield', tag: 'supply', title: 'Compiled languages broke task mining', when: 'Java, T14',
    symptom: 'Two Java repositories produced 74 candidates and zero valid tasks.',
    wrong_model: 'The miner was broken, or Java projects just do not have good fixes.',
    cause: 'A fix often adds a method the new tests call. A dynamic language just fails that one test. javac refuses to compile the whole test tree, so the test could never fail cleanly before the fix.',
    fix: 'A compile failure before the fix now counts as failing, with test names read from the diff. The green run still has to prove them, so a wrong guess can only miss a task, never approve a false one.',
    lesson: 'The safety property mattered more than the fix: make the shortcut incapable of a false positive.',
    evidence: 'Six Java tasks validated. The work also exposed a scoring bug that under-scored any parameterised Java test.',
  },
  {
    id: 'silent-empty', tag: 'supply', title: 'A stage that returned nothing looked like a rejection', when: 'Python, T13',
    symptom: 'Every Python candidate was rejected as "no target tests failing before the fix", a suspiciously uniform result.',
    wrong_model: 'Most pull requests are not really bug fixes.',
    cause: 'Test-only dependencies live in an optional extra that a bare install never pulled in, so pytest could not even collect the test file. A test that cannot be collected looks exactly like a test that already passes.',
    fix: "The adapter reads the project's optional-dependency table and installs the test extra when one exists.",
    lesson: 'The most dangerous bug in a validator is one that fails by returning an empty result, because it looks like a legitimate rejection.',
    evidence: 'Roughly 39 candidates across two repositories were all rejected identically before the fix.',
  },
  {
    id: 'infra-vs-model', tag: 'scoring', title: "A model's broken patch was scored as our infrastructure failing", when: 'First real runs, step 7',
    symptom: 'A real model\'s Java patch that did not compile came back as an infrastructure error in six seconds, and infrastructure errors are excluded from the score.',
    wrong_model: 'Compile failures happen in test setup, so they are infrastructure.',
    cause: 'Every earlier check ran only the human patch, which always compiles. Real, imperfect model output was the first thing ever to reach that code path. A second layer: the check matched text in a truncated message, so a long error could push the marker out of view.',
    fix: 'Typed exceptions for compile and collection failures, checked against the untruncated output, and pytest\'s own exit code 4 for Python. The same fix went onto the install stage.',
    lesson: 'Classify on structure, not on a string that can be truncated. And test with real failures, not just the happy path.',
    evidence: 'Left alone, it would have quietly excluded the hardest failures and inflated Java scores.',
  },
  {
    id: 'npm-config', tag: 'environment', title: 'A global npm setting broke every project', when: 'First real runs, step 7',
    symptom: '"No workspaces found" from npm ci and npx, on repositories that have no workspaces.',
    wrong_model: 'First: zod declares a workspaces field while using pnpm. Then: a network blip.',
    cause: "This machine's own ~/.npmrc contained workspaces=true, forcing every npm command into workspace mode. Found by tracing npm's own stack down to the source file that throws, not by reading the error text.",
    fix: 'Force npm_config_workspaces=false in every subprocess environment, and call the test runner binary directly instead of through npx.',
    lesson: 'The first explanation was true but not causal. Read the tool as a program before accepting a plausible story.',
    evidence: 'The earlier write-up of this bug was corrected in place once the real cause was found.',
  },
  {
    id: 'nvm-network', tag: 'environment', title: 'nvm install touched the network on every call', when: 'First real runs, step 7',
    symptom: 'One identical infrastructure error, dismissed as a flake. The next check-in found thirty in a row.',
    wrong_model: 'A one-off network blip that needs no code change.',
    cause: 'nvm install resolves the version against the remote index before it checks whether the version is already installed. Every attempt therefore depended on the network, and one blip failed a whole batch.',
    fix: 'Check locally first with nvm which, and only fall back to nvm install for a version that is genuinely missing.',
    lesson: 'A flake you cannot reproduce on the spot is not safe to dismiss until you know why that call needed the network at all.',
    evidence: '31 corrupted attempts were removed and re-run.',
  },
  {
    id: 'wrong-user', tag: 'infrastructure', title: 'Ollama restarted as the wrong user and served no models', when: 'First real runs, step 7',
    symptom: '127 infrastructure errors in one 15-minute window, all "model not found", each recorded in a fraction of a second.',
    wrong_model: 'The server is up (it answered on /api/tags), so the models must be available.',
    cause: 'After a machine restart Ollama was started by hand as a normal user, which pointed at an empty model folder. The real service runs as its own user with the models elsewhere.',
    fix: 'Start it with OLLAMA_MODELS pointing at the real folder, and check that ollama list shows the expected models before resuming anything.',
    lesson: 'A 200 from the API proves the server is up, not that it is pointed at the right data.',
    evidence: 'A 15-minute watcher caught it. 230 corrupted rows were removed and the run resumed with no rework.',
  },
  {
    id: 'kafka-single', tag: 'infrastructure', title: 'Kafka on one broker never assigned any work', when: 'Scale-out, T15',
    symptom: 'Workers connected and printed "ready", but never received a partition.',
    wrong_model: 'The consumer code was wrong.',
    cause: 'The offsets topic defaults to 3 replicas, which a one-broker cluster can never satisfy, so consumer-group coordination hung silently. Separately, the job topic had been created with a single partition, so two of the three workers sat idle.',
    fix: 'Set the offsets replication factor to 1, and raised the job topic to 6 partitions.',
    lesson: 'A single-node setup of a distributed system needs its own defaults checked.',
    evidence: 'Then verified with concurrent workers and a force-killed pod: nothing lost, nothing duplicated across 45 jobs.',
  },
  {
    id: 'zero-percent', tag: 'scoring', title: 'A uniform 0% that turned out not to be a bug', when: 'First real runs, step 7',
    symptom: 'After 420 attempts, every model on every task had resolved nothing, including a task one model had solved once in a timing test.',
    wrong_model: 'The scoring is wrong.',
    cause: 'It was not. One task checks two near-identical test variants; the human fix passes both and a partial fix can pass one. The one-off pass was most likely run-to-run variation in local inference. Small local models scoring near zero on hard real bugs is plausible.',
    fix: 'Nothing to fix. Confirmed the human fix resolves every task and an empty patch none, then reported the zeros as the finding they are.',
    lesson: 'Investigate a suspicious uniform result before excusing it, and be ready to believe it after.',
    evidence: '0 of 647 free-model attempts, with 24 of 24 tasks passing the gold and empty gate.',
  },
]
